version: '3.4'
services:
  couchbase:
    build:
      context: .
    container_name: eventing-couchbase
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - ./data:/usr/data
    environment:
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: password
      SERVICES: data,index,query,fts,eventing
